version: "3.7"

services:
  reverse-proxy:
    network_mode: host
    build: ./nginx/
    container_name: flask_nginx
#    ports:
#      - "3000:4000"
    restart: always

  ws-app:
    network_mode: host
    build: ./app1/
    container_name: flask_app
    depends_on:
      - reverse-proxy
    expose:
      - 5100
    restart: always
